build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

run-image-job:
  image: docker.io/android-emulator
  script:
    - cd server && python3 manager.py run_servers immich & && cd ..
    - python3 immich.py immich_x86.apk
  rules:
    - if: '$CI_COMMIT_BRANCH == "deploy"'