build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  timeout: 1h
  tags:
    #- bigmama
    - kvm
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --single-snapshot --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:latest
# --single-snapshot https://github.com/GoogleContainerTools/kaniko/issues/2444

run-image-job:
  # use latest image for now
  image: $CI_REGISTRY_IMAGE:latest
  tags:
    - kvm
  script:
    - export ENVIROMENT=ci
    - echo "Hello, $USER!"
    - cd /home/androidusr/appium
    - echo "Goodbye, $USER!"