build-image-job:
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t android-emulator .
  rules:
    - if: '$CI_COMMIT_BRANCH == "deploy"'

push-image-job:
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push android-emulator
  rules:
    - if: '$CI_COMMIT_BRANCH == "deploy"'

run-image-job:
  image: docker.io/android-emulator
  script:
    - cd server && python3 manager.py run_servers immich & && cd ..
    - python3 immich.py immich_x86.apk
  rules:
    - if: '$CI_COMMIT_BRANCH == "deploy"'